name: Deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Archive project files
        run: zip -r release.zip . -x '*.git*' 'venv/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip -o release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: my-python-app123
          slot-name: Production
          package: .

      - name: Restart Azure App Service
        run: |
          az webapp restart --name my-python-app123 --resource-group ResGrp_Linux
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Auto-bump patch version
        run: |
          VERSION_FILE=app/version.py
          VERSION_LINE=$(grep APP_VERSION $VERSION_FILE)
          VERSION=$(echo $VERSION_LINE | cut -d'"' -f2)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH+1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          echo "APP_VERSION = \"$NEW_VERSION\"" > $VERSION_FILE
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $VERSION_FILE
          git commit -m "🚀 Auto-bump version to $NEW_VERSION"
          git push origin main
  